# Generated by Django 5.2.1 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
